nameApplication: API Gateway
hostApplication: http://localhost

config:
  port: 5000
  enabledMorgan: true

security:
  enabledJSON: true
  enabledHelmet: true

services:
  - nameRoute: user
    url: http://localhost:4000
  - nameRoute: product
    url: http://localhost:3000
