export default {
  token_example:
    'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0Ijp7InVzZXJfaWQiOiIyMzIzZGYzZmQiLCJ1c2VyX3JvbGUiOiJnZXJlbnRlIn0sImV4cCI6MzI0MzI0MjM0MjMsImlhdCI6MTUxNjIzOTAyMn0.CFZH3HYtY1EEODfhMWBsGmKq4sv_GmAwIxSg9jKhGwI',
}
